//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"

	"github.com/guregu/null/v6/zero"
)

type Tasks struct {
	ID          string `sql:"primary_key"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description zero.String
	StartTime   zero.Time `sql:"type:timestamptz"`
	Duration    zero.Int32
	Completed   bool
	Rank        zero.Int32
	ProjectID   zero.String `sql:"project_id"`
}
