// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.0
// Revision: 919e61c0174b91303753ee3898569a01abb32c97
// Build Date: 2023-12-18T15:54:43Z
// Built By: goreleaser

package model

import (
	"fmt"
	"strings"
)

const (
	// IconCat is a Icon of type cat.
	IconCat Icon = "cat"
	// IconRabbit is a Icon of type rabbit.
	IconRabbit Icon = "rabbit"
	// IconSnail is a Icon of type snail.
	IconSnail Icon = "snail"
	// IconSquirrel is a Icon of type squirrel.
	IconSquirrel Icon = "squirrel"
	// IconTurtle is a Icon of type turtle.
	IconTurtle Icon = "turtle"
	// IconBird is a Icon of type bird.
	IconBird Icon = "bird"
	// IconBug is a Icon of type bug.
	IconBug Icon = "bug"
	// IconFish is a Icon of type fish.
	IconFish Icon = "fish"
	// IconRat is a Icon of type rat.
	IconRat Icon = "rat"
	// IconWorm is a Icon of type worm.
	IconWorm Icon = "worm"
	// IconBear is a Icon of type bear.
	IconBear Icon = "bear"
	// IconElephant is a Icon of type elephant.
	IconElephant Icon = "elephant"
	// IconCow is a Icon of type cow.
	IconCow Icon = "cow"
	// IconButterfly is a Icon of type butterfly.
	IconButterfly Icon = "butterfly"
	// IconLion is a Icon of type lion.
	IconLion Icon = "lion"
	// IconCrab is a Icon of type crab.
	IconCrab Icon = "crab"
	// IconFrog is a Icon of type frog.
	IconFrog Icon = "frog"
	// IconHedgehog is a Icon of type hedgehog.
	IconHedgehog Icon = "hedgehog"
	// IconHorse is a Icon of type horse.
	IconHorse Icon = "horse"
	// IconOwl is a Icon of type owl.
	IconOwl Icon = "owl"
	// IconPig is a Icon of type pig.
	IconPig Icon = "pig"
	// IconShark is a Icon of type shark.
	IconShark Icon = "shark"
	// IconWhale is a Icon of type whale.
	IconWhale Icon = "whale"
	// IconNarwhal is a Icon of type narwhal.
	IconNarwhal Icon = "narwhal"
	// IconUnknown is a Icon of type unknown.
	IconUnknown Icon = "unknown"
)

var ErrInvalidIcon = fmt.Errorf("not a valid Icon, try [%s]", strings.Join(_IconNames, ", "))

var _IconNames = []string{
	string(IconCat),
	string(IconRabbit),
	string(IconSnail),
	string(IconSquirrel),
	string(IconTurtle),
	string(IconBird),
	string(IconBug),
	string(IconFish),
	string(IconRat),
	string(IconWorm),
	string(IconBear),
	string(IconElephant),
	string(IconCow),
	string(IconButterfly),
	string(IconLion),
	string(IconCrab),
	string(IconFrog),
	string(IconHedgehog),
	string(IconHorse),
	string(IconOwl),
	string(IconPig),
	string(IconShark),
	string(IconWhale),
	string(IconNarwhal),
	string(IconUnknown),
}

// IconNames returns a list of possible string values of Icon.
func IconNames() []string {
	tmp := make([]string, len(_IconNames))
	copy(tmp, _IconNames)
	return tmp
}

// IconValues returns a list of the values for Icon
func IconValues() []Icon {
	return []Icon{
		IconCat,
		IconRabbit,
		IconSnail,
		IconSquirrel,
		IconTurtle,
		IconBird,
		IconBug,
		IconFish,
		IconRat,
		IconWorm,
		IconBear,
		IconElephant,
		IconCow,
		IconButterfly,
		IconLion,
		IconCrab,
		IconFrog,
		IconHedgehog,
		IconHorse,
		IconOwl,
		IconPig,
		IconShark,
		IconWhale,
		IconNarwhal,
		IconUnknown,
	}
}

// String implements the Stringer interface.
func (x Icon) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Icon) IsValid() bool {
	_, err := ParseIcon(string(x))
	return err == nil
}

var _IconValue = map[string]Icon{
	"cat":       IconCat,
	"rabbit":    IconRabbit,
	"snail":     IconSnail,
	"squirrel":  IconSquirrel,
	"turtle":    IconTurtle,
	"bird":      IconBird,
	"bug":       IconBug,
	"fish":      IconFish,
	"rat":       IconRat,
	"worm":      IconWorm,
	"bear":      IconBear,
	"elephant":  IconElephant,
	"cow":       IconCow,
	"butterfly": IconButterfly,
	"lion":      IconLion,
	"crab":      IconCrab,
	"frog":      IconFrog,
	"hedgehog":  IconHedgehog,
	"horse":     IconHorse,
	"owl":       IconOwl,
	"pig":       IconPig,
	"shark":     IconShark,
	"whale":     IconWhale,
	"narwhal":   IconNarwhal,
	"unknown":   IconUnknown,
}

// ParseIcon attempts to convert a string to a Icon.
func ParseIcon(name string) (Icon, error) {
	if x, ok := _IconValue[name]; ok {
		return x, nil
	}
	return Icon(""), fmt.Errorf("%s is %w", name, ErrInvalidIcon)
}

// MarshalText implements the text marshaller method.
func (x Icon) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Icon) UnmarshalText(text []byte) error {
	tmp, err := ParseIcon(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
