//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Tasks struct {
	ID          *string `sql:"primary_key"`
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	Title       *string
	Description *string
	StartTime   *sql.NullTime
	Duration    *int32
	Completed   *bool
	Rank        *int32
	ProjectId     *uuid.UUID
}
