// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export enum Color {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ColorRed = 0,
    ColorOrange = 1,
    ColorAmber = 2,
    ColorYellow = 3,
    ColorLime = 4,
    ColorGreen = 5,
    ColorEmerald = 6,
    ColorTeal = 7,
    ColorCyan = 8,
    ColorSky = 9,
    ColorViolet = 10,
    ColorPurple = 11,
    ColorFuchsia = 12,
    ColorPink = 13,
    ColorRose = 14,
};

/**
 * Task represents a task in the task tracking application.
 */
export class Task {
    /**
     * Unique identifier for the task
     */
    "id": number;

    /**
     * Color of the task
     */
    "color": Color;

    /**
     * Title of the task
     */
    "title": string;

    /**
     * Description of the task
     */
    "description": string;

    /**
     * Start time of the task
     */
    "startTime": time$0.Time;

    /**
     * Duration of the task
     */
    "duration": time$0.Duration;

    /**
     * Status of task completion
     */
    "completed": boolean;

    /**
     * Timestamp indicating when the task was created.
     */
    "createdAt": time$0.Time;

    /**
     * Timestamp indicating when the task was last updated.
     */
    "updatedAt": time$0.Time;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("color" in $$source)) {
            this["color"] = (0 as Color);
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = null;
        }
        if (!("duration" in $$source)) {
            this["duration"] = (0 as time$0.Duration);
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Task($$parsedSource as Partial<Task>);
    }
}
