// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/pleimann/camel-do/model"

func TaskDialog(task *model.Task) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog x-ref=\"newTaskDialog\" class=\"modal\" open><div class=\"modal-box\"><h3 class=\"text-lg font-bold\">Hello!</h3><form method=\"dialog\"><button class=\"btn btn-circle btn-ghost absolute right-2 top-2 modal-backdrop\">✕</button> <input type=\"text\" placeholder=\"New Task...\" class=\"input input-ghost\"><fieldset class=\"fieldset w-xs bg-base-200 border border-base-300 p-4 rounded-box\"><legend class=\"fieldset-legend\">Task Details</legend> <label class=\"fieldset-label\">Title</label> <input type=\"text\" class=\"input\" placeholder=\"My awesome task\"> <label class=\"fieldset-label\">Description</label> <input type=\"text\" class=\"input\" placeholder=\"my-awesome-task\"> <label class=\"fieldset-label\">Author</label> <input type=\"text\" class=\"input\" placeholder=\"Name\"></fieldset></form></div></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
