// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/pleimann/camel-do/model"
	"github.com/pleimann/camel-do/templates/components"
)

func TaskDialog(projects []model.Project, task *model.Task) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog class=\"modal\" hx-on:htmx:load=\"this.showModal(); document.querySelector(&#39;form#taskForm&#39;).title.focus();\" hx-on:close-modal=\"this.close()\"><div class=\"modal-box w-[20rem] pt-2\"><button class=\"btn btn-circle btn-ghost absolute right-2 top-2 z-1\" onclick=\"htmx.closest(this, &#39;dialog&#39;).remove()\"><i data-lucide=\"x\"></i></button><form id=\"taskForm\" method=\"dialog\" class=\"flex flex-col gap-4\" hx-post=\"/tasks/\"><label class=\"input input-ghost input-lg focus-within:outline-hidden grow\"><i data-lucide=\"pencil-line\" class=\"opacity-50 size-6 -ml-4\"></i> <input name=\"title\" class=\"w-full shrink font-semibold\" type=\"text\" placeholder=\"New Task...\" autocomplete=\"off\"></label><div class=\"join grow\"><input name=\"project\" type=\"text\" placeholder=\"Project\" list=\"projects\" class=\"input join-item grow\"><div class=\"dropdown dropdown-bottom dropdown-end\"><div tabindex=\"0\" role=\"button\" class=\"join-item btn\">▾</div><ul tabindex=\"0\" class=\"dropdown-content menu bg-base-200 rounded-box z-1 w-52 p-2 shadow-sm\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, project := range projects {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<li><a value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(project.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/taskdialog.templ`, Line: 26, Col: 41}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.IconC(project.Icon, project.Color, 8).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(project.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/taskdialog.templ`, Line: 28, Col: 32}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</ul></div></div><textarea name=\"description\" class=\"textarea\" placeholder=\"Notes\"></textarea> <input name=\"start\" type=\"datetime-local\" class=\"input grow\"><div class=\"join grow\"><input name=\"duration\" class=\"join-item input\" value=\"0\"> <button class=\"join-item btn p-2 text-xs font-light\">-15m</button> <button class=\"join-item btn p-2 text-xs font-light\">+15m</button> <button class=\"join-item btn p-2 text-xs font-light\">-1h</button> <button class=\"join-item btn p-2 text-xs font-light\">+1h</button></div><div class=\"w-full max-w-xs\"><input type=\"range\" min=\"0\" max=\"300\" value=\"0\" class=\"range\" step=\"15\"><div class=\"flex justify-between px-2.5 mt-2 text-xs\"><span>|</span> <span>|</span> <span>|</span> <span>&nbsp;</span> <span>|</span> <span>&nbsp;</span> <span>|</span> <span>&nbsp;</span> <span>|</span> <span>&nbsp;&nbsp;&nbsp;</span> <span>|</span> <span>&nbsp;&nbsp;&nbsp;</span> <span>|</span> <span>&nbsp;&nbsp;&nbsp;</span></div><div class=\"flex justify-between px-2.5 mt-2 text-xs\"><span>1m</span> <span>15m</span> <span>30m</span> <span>&nbsp;&nbsp;</span> <span></span> <span>1h</span> <span>&nbsp;</span> <span>1.5h</span> <span>&nbsp;</span> <span>2h</span> <span>&nbsp;&nbsp;&nbsp;</span> <span>3h</span> <span>&nbsp;&nbsp;&nbsp;</span> <span>4h</span> <span>&nbsp;&nbsp;&nbsp;</span> <span>5h</span> <span>&nbsp;&nbsp;&nbsp;</span></div></div><button class=\"btn btn-primary\">Create</button></form></div></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
