// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/pleimann/camel-do/model"

func TaskDialog(task *model.Task) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog class=\"modal\" hx-on:htmx:load=\"this.showModal(); document.querySelector(&#39;form#taskForm&#39;).title.focus();\" hx-on:close-modal=\"this.close()\"><div class=\"modal-box\"><button class=\"btn btn-circle btn-ghost absolute right-2 top-2 modal-backdrop\"><i data-lucide=\"x\"></i></button><form id=\"taskForm\" method=\"dialog\" class=\"flex flex-col gap-4\" hx-post=\"/tasks/\"><input name=\"title\" type=\"text\" placeholder=\"New Task...\" class=\"input input-ghost text-lg w-full font-bold\"><fieldset class=\"fieldset bg-base-200 border border-base-300 p-4 w-full rounded-box\"><legend class=\"fieldset-legend\">Task Details</legend> <label class=\"fieldset-label\">Color <input type=\"text\" class=\"input\" placeholder=\"My awesome task\" name=\"color\"></label> <label class=\"fieldset-label\">Description <textarea name=\"description\" class=\"input w-full h-16 max-h-64\"></textarea></label> <label class=\"fieldset-label\">Duration <input type=\"text\" class=\"input\" placeholder=\"Name\" name=\"duration\"></label></fieldset><button class=\"btn btn-primary btn-lg rounded\">Create</button></form></div></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
