// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class User {
    "Name": string;
    "Email": string;
    "AvatarURL": string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("AvatarURL" in $$source)) {
            this["AvatarURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}
