// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as oauth2$0 from "../../../../../golang.org/x/oauth2/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Authenticate(launcher: any): Promise<$models.User | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1270370337, launcher) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function TokenSource(): Promise<oauth2$0.TokenSource> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3259164740) as any;
    return $resultPromise;
}

export function User(): Promise<$models.User | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(349402847) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $models.User.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
