// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// BodyContent defines HTML content.
func TitleBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"navbar shadow-lg bg-auto w-full p-0 pr-6\"><div class=\"navbar-start\"></div><div class=\"navbar-center\"><a class=\"text-lg font-black font-stretch-125%\">Camel Do</a></div><div class=\"navbar-end flex flex-row gap-4\"><button class=\"btn btn-ghost btn-circle\"><i data-lucide=\"search\" class=\"size-8\"></i></button> <button class=\"btn btn-ghost btn-circle\"><i data-lucide=\"bell\" class=\"size-8\"></i></button> <button class=\"btn btn-ghost btn-circle\"><i data-lucide=\"refresh\" class=\"size-8\"></i></button> <label class=\"btn btn-ghost btn-circle swap swap-rotate\"><input type=\"checkbox\" value=\"dark\" class=\"theme-controller\" id=\"theme-controller\"> <i data-lucide=\"sun\" class=\"size-8 swap-on\"></i> <i data-lucide=\"moon\" class=\"size-8 swap-off\"></i></label><div class=\"avatar avatar-placeholder cursor-pointer\"><div class=\"bg-secondary text-secondary-content dark:bg-neutral dark:text-neutral-content size-8 rounded-full\"><span>MP</span></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
