// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function Apple(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1327721710) as any;
    return $resultPromise;
}

export function CallableByJS(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3933901408) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function Github(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(263188833) as any;
    return $resultPromise;
}

export function Google(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4091434993) as any;
    return $resultPromise;
}

export function InjectJS(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1683667828) as any;
    return $resultPromise;
}

export function LogoutApple(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(381001212) as any;
    return $resultPromise;
}

export function LogoutGithub(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1984673003) as any;
    return $resultPromise;
}

export function LogoutGoogle(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1580212563) as any;
    return $resultPromise;
}

export function LogoutMicrosoftOnline(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2671524787) as any;
    return $resultPromise;
}

export function LogoutOkta(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4252785613) as any;
    return $resultPromise;
}

export function LogoutOnedrive(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2223670080) as any;
    return $resultPromise;
}

export function LogoutOpenIDConnect(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3567218989) as any;
    return $resultPromise;
}

export function LogoutSlack(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1173373220) as any;
    return $resultPromise;
}

export function LogoutZoom(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2215535815) as any;
    return $resultPromise;
}

export function MicrosoftOnline(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(927805305) as any;
    return $resultPromise;
}

export function Name(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3841940001) as any;
    return $resultPromise;
}

export function Okta(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(604027179) as any;
    return $resultPromise;
}

export function Onedrive(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(102271974) as any;
    return $resultPromise;
}

export function OpenIDConnect(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2111805843) as any;
    return $resultPromise;
}

export function Shutdown(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1047962140) as any;
    return $resultPromise;
}

export function Slack(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3042406562) as any;
    return $resultPromise;
}

export function Zoom(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(207117889) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
